---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: security-dev
spec:
  encryptedData:
    admin-password: AgCO/XWV7FExrzo2XHz19PxNPiLjPCr573V83YTsdtqsp+7FkVHrshkaJSdZ5ywjc/JDdMdpAbv4vArjxt5hn/02F+hZWEYu7AK2cWL5s8fCyNPneMA3MbJ0PKG1CTkUWt0AHl+GdM16MOwEwAoH/n7tk4BWSUywRwpaTt4YTCD0Bh3VW46u9PE68qfkjVbBcAIlwwNbUjq68sofyKFmM2El9NEVe6XyzLOwUv7gMnxk2p+Rpyk/+wu6geqJuZO8RTNEKid1BnF7VVLdwPRnx48TkPDww191zi/xug8SVelGiTA6tD3IEGsVD9zR9kt803UOu9oRdVg7pVttP9zMqC57ev2uAD+xFR3+Ajgo/peFHnHyprPLPe78YUzyEdyhUJrt4GOFcyPCViWZsRhHQXUadQzbaYh0AuXEVg1jYgaWfnBA8sVZ5kpLLTvHM+l2kprMp5O21eq6Mf8D+T/IzFJFI2MoKsEHnMLfFSjlrxqQ3n3znZthVYOjhQaTrS5t0A08tsghxyVafEpMZYeVa+oF4zTZ+Oo0RfUuHjK/ExJoVeDghJrtaXQ62dJ5lGK14d0h84MFMg4UXjYIiB47f2cCnKEURXUvWzyq0Q1Gk+L7Mq/PINntQLV8J1bQj5Gmdme+sUvlF0un5dZFRPPXryTN+YuoazW0k0Th0epADvcO1c28Lc5IMFsnsCvyQq78Shkr0JBT07wvtfE2cz9xWsK67B6Ahg==
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: security-dev
    type: Opaque
