{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: {{ .Values.sealedSecret.encryptedData.AUTHENTIK_SECRET_KEY | quote }}
    AUTHENTIK_POSTGRESQL__PASSWORD: {{ .Values.sealedSecret.encryptedData.AUTHENTIK_POSTGRESQL__PASSWORD | quote }}
    AUTHENTIK_BOOTSTRAP_PASSWORD: {{ .Values.sealedSecret.encryptedData.AUTHENTIK_BOOTSTRAP_PASSWORD | quote }}
    AUTHENTIK_BOOTSTRAP_TOKEN: {{ .Values.sealedSecret.encryptedData.AUTHENTIK_BOOTSTRAP_TOKEN | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: authentik
        app.kubernetes.io/instance: {{ .Release.Name }}
    type: Opaque
{{- end }}
