---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-postgres-app
  namespace: data-dev
spec:
  encryptedData:
    password: AgBRsEWrHhffQq0slDQmsJvGs8bgatFLHKufxEVi19T59OL8ypgzdFIpkHtC5mWPruuVcznx0UqgCXZnkmnaXDoFETTMlXrcEPYSCQMbcp2Uld0M7aM2Q39/7VDBlbj3qZG4IlCI8kCvXKiF3dyGEXrmoHyLjTaXz4DLgup7CZPt6R6DV1dQ7uGxkjerw+JBNxxuVYmuUaT7cVyXWL79si9a6e7e332Q3koWG66+4oO1DMmEgBC35rIDuJMEfQpFRsOsVzEHLdzZdYLKkZhmBKxDV7K/3tf8kn5DCTFHergZveBh0rOYYyJN0DA5GAIiblN6BYHJ+qxKWnW0y00Qe6SYmJAvMUl7Odj7fUUVzp9nfCDZ2EciDARgK8W3OFmg7Js7j/T3S4GQUi1o5JwNRKM4v5STgGo6twnWosegbMcZ2hTaQkNWIek8N/FTnNTkNtGjzxST7V4QFg64Izk4FZu/w5bBZvX9H78ZEEv1udnTaoOh82BTOPbxlRTJ3CvaJ2oR/IrqTMF0w55vOXS+CJstZPz9ObOxLccw0C84E50vGiWh39jedJc13Z+GZESD27D+AgMrHHm1pf9ygTOVeCX9jFAxyKUCI4oZ0fV5pvX/xUzSTe9BeMULWCOdNRfVqIlEC+zwx67cMct/g88W9NAz6F77FgfNsYERmD6VkEDLEr2WNzEpH/Q+4yPwNh746X87HmrdkxTaonLx2q3PpXMLABmdFA==
    username: AgAyrgE9rX1hPF5IgMz9tQ0PZKUhQq+EQc3Vki/a9qu9xnfdKY+FkaEpVWK1+KzzUL8irGJ+IrkgfAbOSpeWnYWo5FBbC4q1O4pCds3YAnM6+5mVZqhaYB09nu99lZi/bhcWvv/GJjntcCGP5mra85483xG/cK+S7cQihokT/gyIcKxSyn3joP595YcvFX/10aFvaY5cfY8/RKtIGCE9rIR6kHtullQ33TTy5XZ347NKLV3AohRQKjhVkL/A1a3PyvlNNXmKAnB1+el5d5QeFGcjrcYxrhPZtTo3fa2BR2+FPX28Tpm1L4gdBuBcZklcQ9KW4Mild0qKkjjs7L1TBAZLNwYO2Di/Q8AcSUicwU1EmiBgmWrfJuCqK8v2tsb7KWZ8nLzt+IrHeOgTtbyhwK9fi9JgX6BOBbij2Fl9Kh5VvlCq4RUV7jPqAd64sWqNmL8tT9F0ce0QlNgj/Rgpkjh0vc0GsDtVjt4MnkfAxFVv1BwE8zmHHTt5HuOOOTFQO0+mN6iSKGGw+Jw66ZaEZPphtPpQ8v+K0q952/ZNZL6DFBeBsqIp4rjS5G2HL8PYs9rQc8/WG1qoYlJBaZPKhSHLh6aFUJYW2cr8OKaNh9VsGZcVbXMkxq7DSbN0IX97bxydElM6jtGp+pPPb6oiKHjkNqXQmYs/VLY1fGHcmt7ftaprHi/SycLopSEzKtSiE4xFiIypZy9wyg==
  template:
    metadata:
      name: platform-postgres-app
      namespace: data-dev
    type: kubernetes.io/basic-auth
