# Local Development Environment Configuration
# Namespace: security-dev
# Deployment: local k3s cluster with Longhorn storage

keycloak:
  fullnameOverride: keycloak-dev

  replicaCount: 1

  auth:
    adminUser: admin
    existingSecret: "keycloak-admin-credentials"
    passwordSecretKey: "admin-password"

  production: false

  postgresql:
    enabled: false

  externalDatabase:
    host: "platform-postgres-dev-rw.data-dev.svc.cluster.local"
    port: 5432
    database: "keycloak_dev"
    existingSecret: "keycloak-db-credentials"
    existingSecretUserKey: "db-user"
    existingSecretPasswordKey: "db-password"
    namespace: "data-dev"

  service:
    type: ClusterIP

  ingress:
    enabled: false

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

  podLabels:
    app.kubernetes.io/part-of: security-platform
    environment: dev
    deployment: local

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: keycloak
            topologyKey: kubernetes.io/hostname

  persistence:
    storageClass: "longhorn"

sealedSecret:
  enabled: true
  dbCredentials:
    name: keycloak-db-credentials
    encryptedData:
      db-user: AgB4VwhfpQEuI1xQKXzzgZkWRfVrZSL9LlJ6cMpi7/GVQjwVcDOE7FRrN4Z82IWovcc5H/+t9tlSqXLf3497HQEVJeJ3/x4YAmWdaRr4tX/1sY948ywNSfK9cmymFgHPgyiP6ZKDFZsOLrYioPU6VShuSP8ONNeM2yyAX6Pd+G43fx53if2BMT/4QTNm9ltqfHDrq37UqHhC7P0/G2hwGUXA1EgeWRd4Y3XDqNY11UXm30nUC3HlY2GgTfmsrNgMQd2MxAkcYoAMMoDhMt6kVMS+TpfDu0Ghj+KxN4179pEPOE+/FxXkpnrMkx4bA8DVdoobfEggH8yTNJepdHmMDSrJLnxRnaMkG3CEpegksW53a7dcxEG1m8/wPPGvdSz6F3IFKs2Y+zCxKpgCCPyR8QlLCjZbL1u9C3+kzAuyK3OuCQclcaKP3HMGCjdsMsOqSXKMeNPr77h26so9o4ZBgdGLKx7/bH2fT+4KohHdrJiS3qA1rkICcsfaVaAwOrpwEnWLg68dj3d6280Iia7QW3B62E1HQ2ygwGg9jeEpZxBN63HjBkG41RxWZnDU0hOVrSVHOWT5WTCriCtunjix9nr6gQmIIlz4RZVQ16yJgnnk+q+UqeDyoVpHVNj3cl8LRD89fe+7aUoP+YH8Srp9oCQzTR+1FKwVp2EFsCN0kuCU3aeB2TfJ22x8PESu3Z1zgf3toj9g9bYYMR3tZvzEmyTDfH0aLw==
      db-password: AgA3gj5vPvd9kyGFKo0FaANMK5tmaXsx2WQTkFWlK/nuvt+2hpRKCSHOT4fSwHotdbs0YqiHQWgdSK+nLt7pnLMwk1BxJ4tTtiJOAZbaTl/RHoA3J6fxTUxQ1Qbr+nvVJcnO8zTpJI6FfN+iKsK6QuBcmX+YTctig7F9C/bzXCP4EYih3H2+YVyq5YNw+7o2NNNxDYiQZrMAJd+MxU7fq7KIGzD+n9lOVXSzxGrD0wIGGbacUE36OlprYauV7/yRkpO7nutsTQcVJ8uUkHSFZCec7QkHqH5yH8X9kNJkFqEPxT78VjMXBgSjz3HM6DmcV9+XQv0MlQwMIH6R9RqremYUYH8JAl9atWCd5tqmmhpcYjt0i07GUMsRSedaxjbvdk3R1a4N77pDJLkjLCZ4pmmG06PqifijA19jLbwerXWCwdJ7Oa/iNvK64Zfucv0xCLqvtcokkoXj37APkpOISdGzwDcgT4/f00B7HPX7RhA66Ur/EQyh4QeKhi3Z7RCh44aQ0ZWGaxEj5img/2al474E2HIG0QJW9hU6K1yVJySRTEH3VzjypJa4vS/wDaL2RTh1PIeleNGZauviyIRLR5G4v6pwTX+8KpDxV+aVfRUpm1zVG/Y1FqNWO0BIo28cVn4OHlEvYbBGq7c78ZGIZkzovsT9WNboeZHbe9HiqK77mtQvqPwhLWEVOD0rBl+IjhtKumLEe8Jiggi1vNQ=
  adminCredentials:
    name: keycloak-admin-credentials
    encryptedData:
      admin-password: AgCO/XWV7FExrzo2XHz19PxNPiLjPCr573V83YTsdtqsp+7FkVHrshkaJSdZ5ywjc/JDdMdpAbv4vArjxt5hn/02F+hZWEYu7AK2cWL5s8fCyNPneMA3MbJ0PKG1CTkUWt0AHl+GdM16MOwEwAoH/n7tk4BWSUywRwpaTt4YTCD0Bh3VW46u9PE68qfkjVbBcAIlwwNbUjq68sofyKFmM2El9NEVe6XyzLOwUv7gMnxk2p+Rpyk/+wu6geqJuZO8RTNEKid1BnF7VVLdwPRnx48TkPDww191zi/xug8SVelGiTA6tD3IEGsVD9zR9kt803UOu9oRdVg7pVttP9zMqC57ev2uAD+xFR3+Ajgo/peFHnHyprPLPe78YUzyEdyhUJrt4GOFcyPCViWZsRhHQXUadQzbaYh0AuXEVg1jYgaWfnBA8sVZ5kpLLTvHM+l2kprMp5O21eq6Mf8D+T/IzFJFI2MoKsEHnMLfFSjlrxqQ3n3znZthVYOjhQaTrS5t0A08tsghxyVafEpMZYeVa+oF4zTZ+Oo0RfUuHjK/ExJoVeDghJrtaXQ62dJ5lGK14d0h84MFMg4UXjYIiB47f2cCnKEURXUvWzyq0Q1Gk+L7Mq/PINntQLV8J1bQj5Gmdme+sUvlF0un5dZFRPPXryTN+YuoazW0k0Th0epADvcO1c28Lc5IMFsnsCvyQq78Shkr0JBT07wvtfE2cz9xWsK67B6Ahg==

networkPolicy:
  enabled: true
