{{- if .Values.sealedSecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.dbCredentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    db-user: {{ index .Values.sealedSecret.dbCredentials.encryptedData "db-user" | quote }}
    db-password: {{ index .Values.sealedSecret.dbCredentials.encryptedData "db-password" | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.dbCredentials.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ include "keycloak.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.adminCredentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    admin-password: {{ index .Values.sealedSecret.adminCredentials.encryptedData "admin-password" | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.adminCredentials.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ include "keycloak.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    type: Opaque
{{- end }}
