{{- if .Values.sealedSecret.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  encryptedData:
    KEYCLOAK_ADMIN: {{ .Values.sealedSecret.encryptedData.KEYCLOAK_ADMIN | quote }}
    KEYCLOAK_ADMIN_PASSWORD: {{ .Values.sealedSecret.encryptedData.KEYCLOAK_ADMIN_PASSWORD | quote }}
    KC_DB: {{ .Values.sealedSecret.encryptedData.KC_DB | quote }}
    KC_DB_USERNAME: {{ .Values.sealedSecret.encryptedData.KC_DB_USERNAME | quote }}
    KC_DB_PASSWORD: {{ .Values.sealedSecret.encryptedData.KC_DB_PASSWORD | quote }}
    KC_DB_URL_HOST: {{ .Values.sealedSecret.encryptedData.KC_DB_URL_HOST | quote }}
    KC_DB_URL_PORT: {{ .Values.sealedSecret.encryptedData.KC_DB_URL_PORT | quote }}
    KC_DB_URL_DATABASE: {{ .Values.sealedSecret.encryptedData.KC_DB_URL_DATABASE | quote }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ include "keycloak.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    type: Opaque
{{- end }}
